//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YukiBox.Desktop.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YukiBox.Desktop.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string MsgBox_Cancel {
            get {
                return ResourceManager.GetString("MsgBox.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string MsgBox_No {
            get {
                return ResourceManager.GetString("MsgBox.No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string MsgBox_Ok {
            get {
                return ResourceManager.GetString("MsgBox.Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string MsgBox_Yes {
            get {
                return ResourceManager.GetString("MsgBox.Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Nav_About {
            get {
                return ResourceManager.GetString("Nav.About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Page.
        /// </summary>
        public static string Nav_About_Tooltip {
            get {
                return ResourceManager.GetString("Nav.About.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string Nav_Setting {
            get {
                return ResourceManager.GetString("Nav.Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting Page.
        /// </summary>
        public static string Nav_Setting_Tooltip {
            get {
                return ResourceManager.GetString("Nav.Setting.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taskbar Tweak.
        /// </summary>
        public static string Nav_Taskbar {
            get {
                return ResourceManager.GetString("Nav.Taskbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taskbar Tweak Page.
        /// </summary>
        public static string Nav_Taskbar_Tooltip {
            get {
                return ResourceManager.GetString("Nav.Taskbar.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An application thats contains sort of tools. Welcome to use and provide suggestions..
        /// </summary>
        public static string System_About_Description {
            get {
                return ResourceManager.GetString("System.About.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string System_About_Feedback {
            get {
                return ResourceManager.GetString("System.About.Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send me an issues.
        /// </summary>
        public static string System_About_Feedback_Des {
            get {
                return ResourceManager.GetString("System.About.Feedback.Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Code.
        /// </summary>
        public static string System_About_Github_Des {
            get {
                return ResourceManager.GetString("System.About.Github.Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: .
        /// </summary>
        public static string System_About_Version {
            get {
                return ResourceManager.GetString("System.About.Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YukiBox.
        /// </summary>
        public static string System_AppName {
            get {
                return ResourceManager.GetString("System.AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string System_Language {
            get {
                return ResourceManager.GetString("System.Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Default.
        /// </summary>
        public static string System_Language_Default {
            get {
                return ResourceManager.GetString("System.Language.Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Application To Apply Changes..
        /// </summary>
        public static string System_Restart {
            get {
                return ResourceManager.GetString("System.Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run at startup.
        /// </summary>
        public static string System_RunAtStartUp {
            get {
                return ResourceManager.GetString("System.RunAtStartUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled By User, Please Enable Manually..
        /// </summary>
        public static string System_RunAtStartUp_Disabled {
            get {
                return ResourceManager.GetString("System.RunAtStartUp.Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Toggle Run At StartUp..
        /// </summary>
        public static string System_RunAtStartUp_Error {
            get {
                return ResourceManager.GetString("System.RunAtStartUp.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all settings to default.
        /// </summary>
        public static string System_Setting_Restore {
            get {
                return ResourceManager.GetString("System.Setting.Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Settings.
        /// </summary>
        public static string System_Setting_Save {
            get {
                return ResourceManager.GetString("System.Setting.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NetEase Cloud Music.
        /// </summary>
        public static string Taskbar_Player_CloudMusic {
            get {
                return ResourceManager.GetString("Taskbar.Player.CloudMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QQMusic.
        /// </summary>
        public static string Taskbar_Player_QQMusic {
            get {
                return ResourceManager.GetString("Taskbar.Player.QQMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searchbox.
        /// </summary>
        public static string Taskbar_Searchbox {
            get {
                return ResourceManager.GetString("Taskbar.Searchbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Follow Music Player:.
        /// </summary>
        public static string Taskbar_Searchbox_CheckingPlayer {
            get {
                return ResourceManager.GetString("Taskbar.Searchbox.CheckingPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartIsBack++ Compatibility Mode.
        /// </summary>
        public static string Taskbar_Searchbox_CompatibleStartIsBack {
            get {
                return ResourceManager.GetString("Taskbar.Searchbox.CompatibleStartIsBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Text When No Music Playing:.
        /// </summary>
        public static string Taskbar_Searchbox_DefaultText {
            get {
                return ResourceManager.GetString("Taskbar.Searchbox.DefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Searchbox Music Name Display.
        /// </summary>
        public static string Taskbar_Searchbox_EnableMusicUpdate {
            get {
                return ResourceManager.GetString("Taskbar.Searchbox.EnableMusicUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string ToggleButton_Off {
            get {
                return ResourceManager.GetString("ToggleButton.Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string ToggleButton_On {
            get {
                return ResourceManager.GetString("ToggleButton.On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string TrayIcon_Exit {
            get {
                return ResourceManager.GetString("TrayIcon.Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string TrayIcon_Exit_Tooltip {
            get {
                return ResourceManager.GetString("TrayIcon.Exit.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Main Window.
        /// </summary>
        public static string TrayIcon_Main {
            get {
                return ResourceManager.GetString("TrayIcon.Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Main Window.
        /// </summary>
        public static string TrayIcon_Main_Tooltip {
            get {
                return ResourceManager.GetString("TrayIcon.Main.Tooltip", resourceCulture);
            }
        }
    }
}
