//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YukiBox.Desktop.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YukiBox.Desktop.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string MsgBox_Cancel {
            get {
                return ResourceManager.GetString("MsgBox.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        public static string MsgBox_No {
            get {
                return ResourceManager.GetString("MsgBox.No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string MsgBox_Ok {
            get {
                return ResourceManager.GetString("MsgBox.Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        public static string MsgBox_Yes {
            get {
                return ResourceManager.GetString("MsgBox.Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string Nav_About {
            get {
                return ResourceManager.GetString("Nav.About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About Page 的本地化字符串。
        /// </summary>
        public static string Nav_About_Tooltip {
            get {
                return ResourceManager.GetString("Nav.About.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting 的本地化字符串。
        /// </summary>
        public static string Nav_Setting {
            get {
                return ResourceManager.GetString("Nav.Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting Page 的本地化字符串。
        /// </summary>
        public static string Nav_Setting_Tooltip {
            get {
                return ResourceManager.GetString("Nav.Setting.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Taskbar Tweak 的本地化字符串。
        /// </summary>
        public static string Nav_Taskbar {
            get {
                return ResourceManager.GetString("Nav.Taskbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Taskbar Tweak Page 的本地化字符串。
        /// </summary>
        public static string Nav_Taskbar_Tooltip {
            get {
                return ResourceManager.GetString("Nav.Taskbar.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An application thats contains sort of tools. Welcome to use and provide suggestions. 的本地化字符串。
        /// </summary>
        public static string System_About_Description {
            get {
                return ResourceManager.GetString("System.About.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Feedback 的本地化字符串。
        /// </summary>
        public static string System_About_Feedback {
            get {
                return ResourceManager.GetString("System.About.Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send me an issues 的本地化字符串。
        /// </summary>
        public static string System_About_Feedback_Des {
            get {
                return ResourceManager.GetString("System.About.Feedback.Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Source Code 的本地化字符串。
        /// </summary>
        public static string System_About_Github_Des {
            get {
                return ResourceManager.GetString("System.About.Github.Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version:  的本地化字符串。
        /// </summary>
        public static string System_About_Version {
            get {
                return ResourceManager.GetString("System.About.Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 YukiBox 的本地化字符串。
        /// </summary>
        public static string System_AppName {
            get {
                return ResourceManager.GetString("System.AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string System_Language {
            get {
                return ResourceManager.GetString("System.Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System Default 的本地化字符串。
        /// </summary>
        public static string System_Language_Default {
            get {
                return ResourceManager.GetString("System.Language.Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restart Application To Apply Changes. 的本地化字符串。
        /// </summary>
        public static string System_Restart {
            get {
                return ResourceManager.GetString("System.Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run at startup 的本地化字符串。
        /// </summary>
        public static string System_RunAtStartUp {
            get {
                return ResourceManager.GetString("System.RunAtStartUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disabled By User, Please Enable Manually. 的本地化字符串。
        /// </summary>
        public static string System_RunAtStartUp_Disabled {
            get {
                return ResourceManager.GetString("System.RunAtStartUp.Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot Toggle Run At StartUp. 的本地化字符串。
        /// </summary>
        public static string System_RunAtStartUp_Error {
            get {
                return ResourceManager.GetString("System.RunAtStartUp.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Additional 的本地化字符串。
        /// </summary>
        public static string System_Setting_Additional {
            get {
                return ResourceManager.GetString("System.Setting.Additional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit YukiBox 的本地化字符串。
        /// </summary>
        public static string System_Setting_AppExit {
            get {
                return ResourceManager.GetString("System.Setting.AppExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General Behavior 的本地化字符串。
        /// </summary>
        public static string System_Setting_General {
            get {
                return ResourceManager.GetString("System.Setting.General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset all settings to default 的本地化字符串。
        /// </summary>
        public static string System_Setting_Restore {
            get {
                return ResourceManager.GetString("System.Setting.Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Settings 的本地化字符串。
        /// </summary>
        public static string System_Setting_Save {
            get {
                return ResourceManager.GetString("System.Setting.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NetEase Cloud Music 的本地化字符串。
        /// </summary>
        public static string Taskbar_Player_CloudMusic {
            get {
                return ResourceManager.GetString("Taskbar.Player.CloudMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QQMusic 的本地化字符串。
        /// </summary>
        public static string Taskbar_Player_QQMusic {
            get {
                return ResourceManager.GetString("Taskbar.Player.QQMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Searchbox 的本地化字符串。
        /// </summary>
        public static string Taskbar_Searchbox {
            get {
                return ResourceManager.GetString("Taskbar.Searchbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check Follow Music Player: 的本地化字符串。
        /// </summary>
        public static string Taskbar_Searchbox_CheckingPlayer {
            get {
                return ResourceManager.GetString("Taskbar.Searchbox.CheckingPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StartIsBack++ Compatibility Mode 的本地化字符串。
        /// </summary>
        public static string Taskbar_Searchbox_CompatibleStartIsBack {
            get {
                return ResourceManager.GetString("Taskbar.Searchbox.CompatibleStartIsBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default Text When No Music Playing: 的本地化字符串。
        /// </summary>
        public static string Taskbar_Searchbox_DefaultText {
            get {
                return ResourceManager.GetString("Taskbar.Searchbox.DefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Searchbox Music Name Display 的本地化字符串。
        /// </summary>
        public static string Taskbar_Searchbox_EnableMusicUpdate {
            get {
                return ResourceManager.GetString("Taskbar.Searchbox.EnableMusicUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Taskbar 的本地化字符串。
        /// </summary>
        public static string Taskbar_Taskbar {
            get {
                return ResourceManager.GetString("Taskbar.Taskbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mouse wheel adjusts the volume when pointer hover over taskbar 的本地化字符串。
        /// </summary>
        public static string Taskbar_Taskbar_WheelVolume {
            get {
                return ResourceManager.GetString("Taskbar.Taskbar.WheelVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        public static string ToggleButton_Off {
            get {
                return ResourceManager.GetString("ToggleButton.Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        public static string ToggleButton_On {
            get {
                return ResourceManager.GetString("ToggleButton.On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string TrayIcon_Exit {
            get {
                return ResourceManager.GetString("TrayIcon.Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string TrayIcon_Exit_Tooltip {
            get {
                return ResourceManager.GetString("TrayIcon.Exit.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Main Window 的本地化字符串。
        /// </summary>
        public static string TrayIcon_Main {
            get {
                return ResourceManager.GetString("TrayIcon.Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Main Window 的本地化字符串。
        /// </summary>
        public static string TrayIcon_Main_Tooltip {
            get {
                return ResourceManager.GetString("TrayIcon.Main.Tooltip", resourceCulture);
            }
        }
    }
}
